global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # Spring Boot 앱 (IntelliJ로 로컬 실행 중인 것)
  - job_name: 'flag-game'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']

  # Prometheus 자기 자신
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']